name: Deploy to Netlify

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install mdbook (precompiled)
        id: install_mdbook
        run: |
          VERSION="v0.4.43"
          ARCH="x86_64-unknown-linux-gnu"
          URL="https://github.com/rust-lang/mdBook/releases/download/$VERSION/mdbook-$VERSION-$ARCH.tar.gz"
          EXPECTED_SHA="49823b7968d737b865bdd559b6671baa8aa8ec5f"
          FILE="mdbook"

          # Attempt to download and verify the precompiled binary
          echo "Downloading $URL..."
          if curl -fsSL "$URL" -o mdbook.tar.gz; then
            echo "Verifying SHA-1 hash..."
            ACTUAL_SHA=$(sha1sum mdbook.tar.gz | awk '{print $1}')
            if [ "$ACTUAL_SHA" = "$EXPECTED_SHA" ]; then
              echo "SHA-1 verified. Extracting..."
              tar -xzf mdbook.tar.gz
              chmod +x $FILE
              mv $FILE /usr/local/bin/
              echo "Precompiled mdbook installed successfully."
            else
              echo "Hash mismatch! Expected: $EXPECTED_SHA, Got: $ACTUAL_SHA"
              exit 1
            fi
          else
            echo "Failed to download precompiled mdbook."
            exit 1
          fi
        continue-on-error: true

      - name: Install mdbook (building from source)
        if: steps.install_mdbook.outcome == 'failure'
        run: |
          sudo apt-get install -y rustup
          rustup default stable
          rustup update
          cargo install mdbook

      - name: Build documentation with mdbook
        run: mdbook build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
